spring:
  application:
    name: basket-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: basket-service
    redis:
      host: localhost
      port: 6379
      password: sa
  cache:
    redis:
      time-to-live: 60000

basket:
  client:
    platzi: https://api.escuelajs.co/api/v1

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    filter: true
    persist-authorization: true
    default-model-expand-depth: 2
    default-model-rendering: example
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  show-actuator: false
  cache:
    disabled: true

logging:
  level:
    org.springdoc: INFO